import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Satisfy} from 'next/font/google'

const satisfy = Satisfy({
  subsets: ['latin'],
  variable:"--satisfy", // Specify subsets (e.g., 'latin', 'cyrillic')
  weight: '400',      // Specify the weight (if available)
})




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<body className={satisfy.variable}>{children}</body>
    
  
   </html>
  );
}
 