import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Satisfy} from 'next/font/google'

const satisfy = Satisfy({
  subsets: ['latin'],
  variable:"--satisfy", // Specify subsets (e.g., 'latin', 'cyrillic')
  weight: '400',      // Specify the weight (if available)
})


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<body className={satisfy.variable}>{children}</body>
    
  
   </html>
  );
}
 