import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Satisfy} from 'next/font/google'
import Footer from "@/components/Footer";

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'


const satisfy = Satisfy({
  subsets: ['latin'],
  variable:"--satisfy", // Specify subsets (e.g., 'latin', 'cyrillic')
  weight: '400',      // Specify the weight (if available)
})




export const metadata: Metadata = {
  title: "Foodtuck",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={satisfy.variable}>
        <body>
          <SignedOut>
            <SignInButton />
          </SignedOut>
        
            <SignedIn>
                    <UserButton />
                  </SignedIn>
          
          {children}
          <Footer/>
        </body>
      </html>
    </ClerkProvider>
  )
}
